/*
MSRC CVRF API

Testing UpdatesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/rhaist/go-MSRC/openapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_UpdatesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UpdatesAPIService Updates", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.UpdatesAPI.Updates(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpdatesAPIService UpdatesCount", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.UpdatesAPI.UpdatesCount(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpdatesAPIService UpdatesGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.UpdatesAPI.UpdatesGet(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpdatesAPIService UpdatesKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.UpdatesAPI.UpdatesKey(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpdatesAPIService UpdatesKeyGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.UpdatesAPI.UpdatesKeyGet(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpdatesAPIService UpdatesKeyGet_1", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.UpdatesAPI.UpdatesKeyGet_0(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpdatesAPIService UpdatesKey_2", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.UpdatesAPI.UpdatesKey_0(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
