/*
 * MSRC Public API
 *
 * This RESTful API can be used to engage the Microsoft Security Response Center (MSRC) in the following ways:    - Get security update summaries and details using the [Common Vulnerability Reporting Framework](https://www.icasi.org/cvrf) (CVRF).    - Report suspected cyberattacks or abuse originating from Microsoft Online Services.    - Notify Microsoft of any planned penetration tests against your Azure assets.    **Sample client code** is available on the Microsoft Security [Updates](https://github.com/microsoft/MSRC-Microsoft-Security-Updates-API) and [Engage](https://github.com/Microsoft/MSRC-Microsoft-Engage-API)   Github repositories.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RequesterInfo information about the requester
type RequesterInfo struct {
	// requester email
	ContactEmail string `json:"contactEmail"`
}

// NewRequesterInfo instantiates a new RequesterInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequesterInfo(contactEmail string) *RequesterInfo {
	this := RequesterInfo{}
	this.ContactEmail = contactEmail
	return &this
}

// NewRequesterInfoWithDefaults instantiates a new RequesterInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequesterInfoWithDefaults() *RequesterInfo {
	this := RequesterInfo{}
	return &this
}

// GetContactEmail returns the ContactEmail field value
func (o *RequesterInfo) GetContactEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContactEmail
}

// GetContactEmailOk returns a tuple with the ContactEmail field value
// and a boolean to check if the value has been set.
func (o *RequesterInfo) GetContactEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContactEmail, true
}

// SetContactEmail sets field value
func (o *RequesterInfo) SetContactEmail(v string) {
	o.ContactEmail = v
}

func (o RequesterInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["contactEmail"] = o.ContactEmail
	}
	return json.Marshal(toSerialize)
}

type NullableRequesterInfo struct {
	value *RequesterInfo
	isSet bool
}

func (v NullableRequesterInfo) Get() *RequesterInfo {
	return v.value
}

func (v *NullableRequesterInfo) Set(val *RequesterInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableRequesterInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableRequesterInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequesterInfo(val *RequesterInfo) *NullableRequesterInfo {
	return &NullableRequesterInfo{value: val, isSet: true}
}

func (v NullableRequesterInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequesterInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
