/*
 * MSRC Public API
 *
 * This RESTful API can be used to engage the Microsoft Security Response Center (MSRC) in the following ways:    - Get security update summaries and details using the [Common Vulnerability Reporting Framework](https://www.icasi.org/cvrf) (CVRF).    - Report suspected cyberattacks or abuse originating from Microsoft Online Services.    - Notify Microsoft of any planned penetration tests against your Azure assets.    **Sample client code** is available on the Microsoft Security [Updates](https://github.com/microsoft/MSRC-Microsoft-Security-Updates-API) and [Engage](https://github.com/Microsoft/MSRC-Microsoft-Engage-API)   Github repositories.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CvrfdocAggregateSeverity struct for CvrfdocAggregateSeverity
type CvrfdocAggregateSeverity struct {
	Namespace *string `json:"Namespace,omitempty"`
	Lang      *string `json:"lang,omitempty"`
	Value     *string `json:"Value,omitempty"`
}

// NewCvrfdocAggregateSeverity instantiates a new CvrfdocAggregateSeverity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCvrfdocAggregateSeverity() *CvrfdocAggregateSeverity {
	this := CvrfdocAggregateSeverity{}
	return &this
}

// NewCvrfdocAggregateSeverityWithDefaults instantiates a new CvrfdocAggregateSeverity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCvrfdocAggregateSeverityWithDefaults() *CvrfdocAggregateSeverity {
	this := CvrfdocAggregateSeverity{}
	return &this
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *CvrfdocAggregateSeverity) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CvrfdocAggregateSeverity) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *CvrfdocAggregateSeverity) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *CvrfdocAggregateSeverity) SetNamespace(v string) {
	o.Namespace = &v
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *CvrfdocAggregateSeverity) GetLang() string {
	if o == nil || o.Lang == nil {
		var ret string
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CvrfdocAggregateSeverity) GetLangOk() (*string, bool) {
	if o == nil || o.Lang == nil {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *CvrfdocAggregateSeverity) HasLang() bool {
	if o != nil && o.Lang != nil {
		return true
	}

	return false
}

// SetLang gets a reference to the given string and assigns it to the Lang field.
func (o *CvrfdocAggregateSeverity) SetLang(v string) {
	o.Lang = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CvrfdocAggregateSeverity) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CvrfdocAggregateSeverity) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CvrfdocAggregateSeverity) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CvrfdocAggregateSeverity) SetValue(v string) {
	o.Value = &v
}

func (o CvrfdocAggregateSeverity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Namespace != nil {
		toSerialize["Namespace"] = o.Namespace
	}
	if o.Lang != nil {
		toSerialize["lang"] = o.Lang
	}
	if o.Value != nil {
		toSerialize["Value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableCvrfdocAggregateSeverity struct {
	value *CvrfdocAggregateSeverity
	isSet bool
}

func (v NullableCvrfdocAggregateSeverity) Get() *CvrfdocAggregateSeverity {
	return v.value
}

func (v *NullableCvrfdocAggregateSeverity) Set(val *CvrfdocAggregateSeverity) {
	v.value = val
	v.isSet = true
}

func (v NullableCvrfdocAggregateSeverity) IsSet() bool {
	return v.isSet
}

func (v *NullableCvrfdocAggregateSeverity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCvrfdocAggregateSeverity(val *CvrfdocAggregateSeverity) *NullableCvrfdocAggregateSeverity {
	return &NullableCvrfdocAggregateSeverity{value: val, isSet: true}
}

func (v NullableCvrfdocAggregateSeverity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCvrfdocAggregateSeverity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
