/*
MSRC CVRF API

Get security updates programmatically using this RESTful API. Sample client code is available on the [Microsoft Security Updates GitHub](https://github.com/microsoft/MSRC-Microsoft-Security-Updates-API). For more details, please visit [msrc.microsoft.com/update-guide](https://msrc.microsoft.com/update-guide).    _**NOTE: If you're looking for the Engage API (CARS), please refer to the new [Abuse Reporting developer portal](https://msrc.microsoft.com/report/developer).**_

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CvrfdocAcknowledgmentName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CvrfdocAcknowledgmentName{}

// CvrfdocAcknowledgmentName struct for CvrfdocAcknowledgmentName
type CvrfdocAcknowledgmentName struct {
	Lang  *string `json:"lang,omitempty"`
	Value *string `json:"Value,omitempty"`
}

// NewCvrfdocAcknowledgmentName instantiates a new CvrfdocAcknowledgmentName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCvrfdocAcknowledgmentName() *CvrfdocAcknowledgmentName {
	this := CvrfdocAcknowledgmentName{}
	return &this
}

// NewCvrfdocAcknowledgmentNameWithDefaults instantiates a new CvrfdocAcknowledgmentName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCvrfdocAcknowledgmentNameWithDefaults() *CvrfdocAcknowledgmentName {
	this := CvrfdocAcknowledgmentName{}
	return &this
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *CvrfdocAcknowledgmentName) GetLang() string {
	if o == nil || IsNil(o.Lang) {
		var ret string
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CvrfdocAcknowledgmentName) GetLangOk() (*string, bool) {
	if o == nil || IsNil(o.Lang) {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *CvrfdocAcknowledgmentName) HasLang() bool {
	if o != nil && !IsNil(o.Lang) {
		return true
	}

	return false
}

// SetLang gets a reference to the given string and assigns it to the Lang field.
func (o *CvrfdocAcknowledgmentName) SetLang(v string) {
	o.Lang = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CvrfdocAcknowledgmentName) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CvrfdocAcknowledgmentName) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CvrfdocAcknowledgmentName) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CvrfdocAcknowledgmentName) SetValue(v string) {
	o.Value = &v
}

func (o CvrfdocAcknowledgmentName) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CvrfdocAcknowledgmentName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Lang) {
		toSerialize["lang"] = o.Lang
	}
	if !IsNil(o.Value) {
		toSerialize["Value"] = o.Value
	}
	return toSerialize, nil
}

type NullableCvrfdocAcknowledgmentName struct {
	value *CvrfdocAcknowledgmentName
	isSet bool
}

func (v NullableCvrfdocAcknowledgmentName) Get() *CvrfdocAcknowledgmentName {
	return v.value
}

func (v *NullableCvrfdocAcknowledgmentName) Set(val *CvrfdocAcknowledgmentName) {
	v.value = val
	v.isSet = true
}

func (v NullableCvrfdocAcknowledgmentName) IsSet() bool {
	return v.isSet
}

func (v *NullableCvrfdocAcknowledgmentName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCvrfdocAcknowledgmentName(val *CvrfdocAcknowledgmentName) *NullableCvrfdocAcknowledgmentName {
	return &NullableCvrfdocAcknowledgmentName{value: val, isSet: true}
}

func (v NullableCvrfdocAcknowledgmentName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCvrfdocAcknowledgmentName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
