/*
MSRC CVRF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FilterQueryOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilterQueryOption{}

// FilterQueryOption struct for FilterQueryOption
type FilterQueryOption struct {
	Context      *ODataQueryContext     `json:"context,omitempty"`
	Validator    map[string]interface{} `json:"validator,omitempty"`
	Compute      *ComputeQueryOption    `json:"compute,omitempty"`
	FilterClause *FilterClause          `json:"filterClause,omitempty"`
	RawValue     NullableString         `json:"rawValue,omitempty"`
}

// NewFilterQueryOption instantiates a new FilterQueryOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterQueryOption() *FilterQueryOption {
	this := FilterQueryOption{}
	return &this
}

// NewFilterQueryOptionWithDefaults instantiates a new FilterQueryOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterQueryOptionWithDefaults() *FilterQueryOption {
	this := FilterQueryOption{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *FilterQueryOption) GetContext() ODataQueryContext {
	if o == nil || IsNil(o.Context) {
		var ret ODataQueryContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterQueryOption) GetContextOk() (*ODataQueryContext, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *FilterQueryOption) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given ODataQueryContext and assigns it to the Context field.
func (o *FilterQueryOption) SetContext(v ODataQueryContext) {
	o.Context = &v
}

// GetValidator returns the Validator field value if set, zero value otherwise.
func (o *FilterQueryOption) GetValidator() map[string]interface{} {
	if o == nil || IsNil(o.Validator) {
		var ret map[string]interface{}
		return ret
	}
	return o.Validator
}

// GetValidatorOk returns a tuple with the Validator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterQueryOption) GetValidatorOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Validator) {
		return map[string]interface{}{}, false
	}
	return o.Validator, true
}

// HasValidator returns a boolean if a field has been set.
func (o *FilterQueryOption) HasValidator() bool {
	if o != nil && !IsNil(o.Validator) {
		return true
	}

	return false
}

// SetValidator gets a reference to the given map[string]interface{} and assigns it to the Validator field.
func (o *FilterQueryOption) SetValidator(v map[string]interface{}) {
	o.Validator = v
}

// GetCompute returns the Compute field value if set, zero value otherwise.
func (o *FilterQueryOption) GetCompute() ComputeQueryOption {
	if o == nil || IsNil(o.Compute) {
		var ret ComputeQueryOption
		return ret
	}
	return *o.Compute
}

// GetComputeOk returns a tuple with the Compute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterQueryOption) GetComputeOk() (*ComputeQueryOption, bool) {
	if o == nil || IsNil(o.Compute) {
		return nil, false
	}
	return o.Compute, true
}

// HasCompute returns a boolean if a field has been set.
func (o *FilterQueryOption) HasCompute() bool {
	if o != nil && !IsNil(o.Compute) {
		return true
	}

	return false
}

// SetCompute gets a reference to the given ComputeQueryOption and assigns it to the Compute field.
func (o *FilterQueryOption) SetCompute(v ComputeQueryOption) {
	o.Compute = &v
}

// GetFilterClause returns the FilterClause field value if set, zero value otherwise.
func (o *FilterQueryOption) GetFilterClause() FilterClause {
	if o == nil || IsNil(o.FilterClause) {
		var ret FilterClause
		return ret
	}
	return *o.FilterClause
}

// GetFilterClauseOk returns a tuple with the FilterClause field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterQueryOption) GetFilterClauseOk() (*FilterClause, bool) {
	if o == nil || IsNil(o.FilterClause) {
		return nil, false
	}
	return o.FilterClause, true
}

// HasFilterClause returns a boolean if a field has been set.
func (o *FilterQueryOption) HasFilterClause() bool {
	if o != nil && !IsNil(o.FilterClause) {
		return true
	}

	return false
}

// SetFilterClause gets a reference to the given FilterClause and assigns it to the FilterClause field.
func (o *FilterQueryOption) SetFilterClause(v FilterClause) {
	o.FilterClause = &v
}

// GetRawValue returns the RawValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FilterQueryOption) GetRawValue() string {
	if o == nil || IsNil(o.RawValue.Get()) {
		var ret string
		return ret
	}
	return *o.RawValue.Get()
}

// GetRawValueOk returns a tuple with the RawValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FilterQueryOption) GetRawValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawValue.Get(), o.RawValue.IsSet()
}

// HasRawValue returns a boolean if a field has been set.
func (o *FilterQueryOption) HasRawValue() bool {
	if o != nil && o.RawValue.IsSet() {
		return true
	}

	return false
}

// SetRawValue gets a reference to the given NullableString and assigns it to the RawValue field.
func (o *FilterQueryOption) SetRawValue(v string) {
	o.RawValue.Set(&v)
}

// SetRawValueNil sets the value for RawValue to be an explicit nil
func (o *FilterQueryOption) SetRawValueNil() {
	o.RawValue.Set(nil)
}

// UnsetRawValue ensures that no value is present for RawValue, not even an explicit nil
func (o *FilterQueryOption) UnsetRawValue() {
	o.RawValue.Unset()
}

func (o FilterQueryOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilterQueryOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Validator) {
		toSerialize["validator"] = o.Validator
	}
	if !IsNil(o.Compute) {
		toSerialize["compute"] = o.Compute
	}
	if !IsNil(o.FilterClause) {
		toSerialize["filterClause"] = o.FilterClause
	}
	if o.RawValue.IsSet() {
		toSerialize["rawValue"] = o.RawValue.Get()
	}
	return toSerialize, nil
}

type NullableFilterQueryOption struct {
	value *FilterQueryOption
	isSet bool
}

func (v NullableFilterQueryOption) Get() *FilterQueryOption {
	return v.value
}

func (v *NullableFilterQueryOption) Set(val *FilterQueryOption) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterQueryOption) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterQueryOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterQueryOption(val *FilterQueryOption) *NullableFilterQueryOption {
	return &NullableFilterQueryOption{value: val, isSet: true}
}

func (v NullableFilterQueryOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterQueryOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
