/*
MSRC CVRF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchQueryOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchQueryOption{}

// SearchQueryOption struct for SearchQueryOption
type SearchQueryOption struct {
	Context       *ODataQueryContext `json:"context,omitempty"`
	ResultClrType *Type              `json:"resultClrType,omitempty"`
	SearchClause  *SearchClause      `json:"searchClause,omitempty"`
	RawValue      NullableString     `json:"rawValue,omitempty"`
}

// NewSearchQueryOption instantiates a new SearchQueryOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchQueryOption() *SearchQueryOption {
	this := SearchQueryOption{}
	return &this
}

// NewSearchQueryOptionWithDefaults instantiates a new SearchQueryOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchQueryOptionWithDefaults() *SearchQueryOption {
	this := SearchQueryOption{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *SearchQueryOption) GetContext() ODataQueryContext {
	if o == nil || IsNil(o.Context) {
		var ret ODataQueryContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchQueryOption) GetContextOk() (*ODataQueryContext, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *SearchQueryOption) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given ODataQueryContext and assigns it to the Context field.
func (o *SearchQueryOption) SetContext(v ODataQueryContext) {
	o.Context = &v
}

// GetResultClrType returns the ResultClrType field value if set, zero value otherwise.
func (o *SearchQueryOption) GetResultClrType() Type {
	if o == nil || IsNil(o.ResultClrType) {
		var ret Type
		return ret
	}
	return *o.ResultClrType
}

// GetResultClrTypeOk returns a tuple with the ResultClrType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchQueryOption) GetResultClrTypeOk() (*Type, bool) {
	if o == nil || IsNil(o.ResultClrType) {
		return nil, false
	}
	return o.ResultClrType, true
}

// HasResultClrType returns a boolean if a field has been set.
func (o *SearchQueryOption) HasResultClrType() bool {
	if o != nil && !IsNil(o.ResultClrType) {
		return true
	}

	return false
}

// SetResultClrType gets a reference to the given Type and assigns it to the ResultClrType field.
func (o *SearchQueryOption) SetResultClrType(v Type) {
	o.ResultClrType = &v
}

// GetSearchClause returns the SearchClause field value if set, zero value otherwise.
func (o *SearchQueryOption) GetSearchClause() SearchClause {
	if o == nil || IsNil(o.SearchClause) {
		var ret SearchClause
		return ret
	}
	return *o.SearchClause
}

// GetSearchClauseOk returns a tuple with the SearchClause field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchQueryOption) GetSearchClauseOk() (*SearchClause, bool) {
	if o == nil || IsNil(o.SearchClause) {
		return nil, false
	}
	return o.SearchClause, true
}

// HasSearchClause returns a boolean if a field has been set.
func (o *SearchQueryOption) HasSearchClause() bool {
	if o != nil && !IsNil(o.SearchClause) {
		return true
	}

	return false
}

// SetSearchClause gets a reference to the given SearchClause and assigns it to the SearchClause field.
func (o *SearchQueryOption) SetSearchClause(v SearchClause) {
	o.SearchClause = &v
}

// GetRawValue returns the RawValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchQueryOption) GetRawValue() string {
	if o == nil || IsNil(o.RawValue.Get()) {
		var ret string
		return ret
	}
	return *o.RawValue.Get()
}

// GetRawValueOk returns a tuple with the RawValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchQueryOption) GetRawValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawValue.Get(), o.RawValue.IsSet()
}

// HasRawValue returns a boolean if a field has been set.
func (o *SearchQueryOption) HasRawValue() bool {
	if o != nil && o.RawValue.IsSet() {
		return true
	}

	return false
}

// SetRawValue gets a reference to the given NullableString and assigns it to the RawValue field.
func (o *SearchQueryOption) SetRawValue(v string) {
	o.RawValue.Set(&v)
}

// SetRawValueNil sets the value for RawValue to be an explicit nil
func (o *SearchQueryOption) SetRawValueNil() {
	o.RawValue.Set(nil)
}

// UnsetRawValue ensures that no value is present for RawValue, not even an explicit nil
func (o *SearchQueryOption) UnsetRawValue() {
	o.RawValue.Unset()
}

func (o SearchQueryOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchQueryOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.ResultClrType) {
		toSerialize["resultClrType"] = o.ResultClrType
	}
	if !IsNil(o.SearchClause) {
		toSerialize["searchClause"] = o.SearchClause
	}
	if o.RawValue.IsSet() {
		toSerialize["rawValue"] = o.RawValue.Get()
	}
	return toSerialize, nil
}

type NullableSearchQueryOption struct {
	value *SearchQueryOption
	isSet bool
}

func (v NullableSearchQueryOption) Get() *SearchQueryOption {
	return v.value
}

func (v *NullableSearchQueryOption) Set(val *SearchQueryOption) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchQueryOption) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchQueryOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchQueryOption(val *SearchQueryOption) *NullableSearchQueryOption {
	return &NullableSearchQueryOption{value: val, isSet: true}
}

func (v NullableSearchQueryOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchQueryOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
