/*
MSRC CVRF API

Get security updates programmatically using this RESTful API. Sample client code is available on the [Microsoft Security Updates GitHub](https://github.com/microsoft/MSRC-Microsoft-Security-Updates-API). For more details, please visit [msrc.microsoft.com/update-guide](https://msrc.microsoft.com/update-guide).    _**NOTE: If you're looking for the Engage API (CARS), please refer to the new [Abuse Reporting developer portal](https://msrc.microsoft.com/report/developer).**_

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ProductTreeGroup struct for ProductTreeGroup
type ProductTreeGroup struct {
	Description *ProductTreeGroupDescription `json:"Description,omitempty"`
	ProductID   []string                     `json:"ProductID,omitempty"`
	GroupID     *string                      `json:"GroupID,omitempty"`
}

// NewProductTreeGroup instantiates a new ProductTreeGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductTreeGroup() *ProductTreeGroup {
	this := ProductTreeGroup{}
	return &this
}

// NewProductTreeGroupWithDefaults instantiates a new ProductTreeGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductTreeGroupWithDefaults() *ProductTreeGroup {
	this := ProductTreeGroup{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProductTreeGroup) GetDescription() ProductTreeGroupDescription {
	if o == nil || isNil(o.Description) {
		var ret ProductTreeGroupDescription
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductTreeGroup) GetDescriptionOk() (*ProductTreeGroupDescription, bool) {
	if o == nil || isNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProductTreeGroup) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given ProductTreeGroupDescription and assigns it to the Description field.
func (o *ProductTreeGroup) SetDescription(v ProductTreeGroupDescription) {
	o.Description = &v
}

// GetProductID returns the ProductID field value if set, zero value otherwise.
func (o *ProductTreeGroup) GetProductID() []string {
	if o == nil || isNil(o.ProductID) {
		var ret []string
		return ret
	}
	return o.ProductID
}

// GetProductIDOk returns a tuple with the ProductID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductTreeGroup) GetProductIDOk() ([]string, bool) {
	if o == nil || isNil(o.ProductID) {
		return nil, false
	}
	return o.ProductID, true
}

// HasProductID returns a boolean if a field has been set.
func (o *ProductTreeGroup) HasProductID() bool {
	if o != nil && !isNil(o.ProductID) {
		return true
	}

	return false
}

// SetProductID gets a reference to the given []string and assigns it to the ProductID field.
func (o *ProductTreeGroup) SetProductID(v []string) {
	o.ProductID = v
}

// GetGroupID returns the GroupID field value if set, zero value otherwise.
func (o *ProductTreeGroup) GetGroupID() string {
	if o == nil || isNil(o.GroupID) {
		var ret string
		return ret
	}
	return *o.GroupID
}

// GetGroupIDOk returns a tuple with the GroupID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductTreeGroup) GetGroupIDOk() (*string, bool) {
	if o == nil || isNil(o.GroupID) {
		return nil, false
	}
	return o.GroupID, true
}

// HasGroupID returns a boolean if a field has been set.
func (o *ProductTreeGroup) HasGroupID() bool {
	if o != nil && !isNil(o.GroupID) {
		return true
	}

	return false
}

// SetGroupID gets a reference to the given string and assigns it to the GroupID field.
func (o *ProductTreeGroup) SetGroupID(v string) {
	o.GroupID = &v
}

func (o ProductTreeGroup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	if !isNil(o.ProductID) {
		toSerialize["ProductID"] = o.ProductID
	}
	if !isNil(o.GroupID) {
		toSerialize["GroupID"] = o.GroupID
	}
	return json.Marshal(toSerialize)
}

type NullableProductTreeGroup struct {
	value *ProductTreeGroup
	isSet bool
}

func (v NullableProductTreeGroup) Get() *ProductTreeGroup {
	return v.value
}

func (v *NullableProductTreeGroup) Set(val *ProductTreeGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableProductTreeGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableProductTreeGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductTreeGroup(val *ProductTreeGroup) *NullableProductTreeGroup {
	return &NullableProductTreeGroup{value: val, isSet: true}
}

func (v NullableProductTreeGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductTreeGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
