/*
MSRC CVRF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// AddressFamily the model 'AddressFamily'
type AddressFamily string

// List of AddressFamily
const (
	UNSPECIFIED             AddressFamily = "Unspecified"
	UNIX                    AddressFamily = "Unix"
	INTER_NETWORK           AddressFamily = "InterNetwork"
	IMP_LINK                AddressFamily = "ImpLink"
	PUP                     AddressFamily = "Pup"
	CHAOS                   AddressFamily = "Chaos"
	NS                      AddressFamily = "NS"
	OSI                     AddressFamily = "Osi"
	ECMA                    AddressFamily = "Ecma"
	DATA_KIT                AddressFamily = "DataKit"
	CCITT                   AddressFamily = "Ccitt"
	SNA                     AddressFamily = "Sna"
	DEC_NET                 AddressFamily = "DecNet"
	DATA_LINK               AddressFamily = "DataLink"
	LAT                     AddressFamily = "Lat"
	HYPER_CHANNEL           AddressFamily = "HyperChannel"
	APPLE_TALK              AddressFamily = "AppleTalk"
	NET_BIOS                AddressFamily = "NetBios"
	VOICE_VIEW              AddressFamily = "VoiceView"
	FIRE_FOX                AddressFamily = "FireFox"
	BANYAN                  AddressFamily = "Banyan"
	ATM                     AddressFamily = "Atm"
	INTER_NETWORK_V6        AddressFamily = "InterNetworkV6"
	CLUSTER                 AddressFamily = "Cluster"
	IEEE12844               AddressFamily = "Ieee12844"
	IRDA                    AddressFamily = "Irda"
	NETWORK_DESIGNERS       AddressFamily = "NetworkDesigners"
	MAX                     AddressFamily = "Max"
	PACKET                  AddressFamily = "Packet"
	CONTROLLER_AREA_NETWORK AddressFamily = "ControllerAreaNetwork"
	UNKNOWN                 AddressFamily = "Unknown"
)

// All allowed values of AddressFamily enum
var AllowedAddressFamilyEnumValues = []AddressFamily{
	"Unspecified",
	"Unix",
	"InterNetwork",
	"ImpLink",
	"Pup",
	"Chaos",
	"NS",
	"Osi",
	"Ecma",
	"DataKit",
	"Ccitt",
	"Sna",
	"DecNet",
	"DataLink",
	"Lat",
	"HyperChannel",
	"AppleTalk",
	"NetBios",
	"VoiceView",
	"FireFox",
	"Banyan",
	"Atm",
	"InterNetworkV6",
	"Cluster",
	"Ieee12844",
	"Irda",
	"NetworkDesigners",
	"Max",
	"Packet",
	"ControllerAreaNetwork",
	"Unknown",
}

func (v *AddressFamily) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AddressFamily(value)
	for _, existing := range AllowedAddressFamilyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AddressFamily", value)
}

// NewAddressFamilyFromValue returns a pointer to a valid AddressFamily
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAddressFamilyFromValue(v string) (*AddressFamily, error) {
	ev := AddressFamily(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AddressFamily: valid values are %v", v, AllowedAddressFamilyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AddressFamily) IsValid() bool {
	for _, existing := range AllowedAddressFamilyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AddressFamily value
func (v AddressFamily) Ptr() *AddressFamily {
	return &v
}

type NullableAddressFamily struct {
	value *AddressFamily
	isSet bool
}

func (v NullableAddressFamily) Get() *AddressFamily {
	return v.value
}

func (v *NullableAddressFamily) Set(val *AddressFamily) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressFamily) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressFamily) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressFamily(val *AddressFamily) *NullableAddressFamily {
	return &NullableAddressFamily{value: val, isSet: true}
}

func (v NullableAddressFamily) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressFamily) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
